{
    "PopoverItems": [{
            "Title": "Add PurchaseOrderItem",
            "OnPress": "/MDKapp/Actions/PurchaseOrderHeaders/NavToPurchaseOrderHeaders_CreatePurchaseOrderItem.action"
        },
        {
            "Title": "Delete",
            "OnPress": "/MDKapp/Rules/PurchaseOrderHeaders/PurchaseOrderHeaders_DeleteConfirmation.js"
        }
    ],
    "_Type": "Action.Type.PopoverMenu"
}